name: mindcare_app
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.0+3
  fl_chart: ^0.69.0
  lottie: ^3.1.2
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.1
  firebase_core: ^3.4.1
  http_parser: 4.0.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  flutter_animate: ^4.5.0
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  mime_type: ^1.0.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  mime: ^1.0.6
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  logger: ^2.4.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/logo.png
    - assets/images/default_avatar.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
