name: mindcare_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de estado e animações
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2

  # Layout e UI
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.52
  flutter_rating_bar: ^4.0.1

  # Integração de mídia e widgets gráficos
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.4.1

  # Notificações e mensagens push
  

  # Funcionalidades de segurança e armazenamento local
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1

  # Conexões de rede e manipulação de dados
  http: ^1.2.2
  http_parser: 4.0.2
  intl: ^0.19.0
  logger: ^2.4.0

  # Manipulação de imagens
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  # Mapas e localização
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  # Utilitários diversos
  email_validator: ^3.0.0
  mime: ^1.0.6
  mime_type: ^1.0.1
  url_launcher: ^6.3.0
  share_plus: ^10.1.1

  # Configurações de ambiente e variáveis de ambiente
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Análise e linting
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default_avatar.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
